### ISSUE TITLE
benchmarking pyopencl backend giving errors

### ISSUE THREAD

**Issue by philass** [diku-dk/futhark-benchmarks#13]
I ran the benchmarks with CUDA and OpenCL successfully. When I ran the same command with pyopencl I got the following
```
[vgh804@gpu02-diku-apl futhark-benchmarks]$ futhark bench accelerate --backend=pyopencl --ignore-files /lib/
Compiling accelerate/ray/trace.fut...
Compiling accelerate/canny/canny.fut...
Compiling accelerate/tunnel/tunnel.fut...
Compiling accelerate/nbody/nbody.fut...
Compiling accelerate/fft/fft.fut...
Compiling accelerate/pagerank/pagerank.fut...
Compiling accelerate/crystal/crystal.fut...
Compiling accelerate/smoothlife/smoothlife.fut...
Compiling accelerate/nbody/nbody-bh.fut...
Compiling accelerate/hashcat/hashcat.fut...
Compiling accelerate/fluid/fluid.fut...
Compiling accelerate/mandelbrot/mandelbrot.fut...
Compiling accelerate/kmeans/kmeans.fut...
Results for accelerate/canny/canny.fut:
dataset data/lena256.in:                                              accelerate/canny/canny failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/canny/canny", line 4031, in <module>
    entry_point_fun()
  File "./accelerate/canny/canny", line 3997, in entry_main
    w_14971, low_14972, high_14973)
  File "./accelerate/canny/canny", line 3897, in futhark_main
    sync(self)
  File "./accelerate/canny/canny", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

dataset data/lena512.in:                                              accelerate/canny/canny failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/canny/canny", line 4031, in <module>
    entry_point_fun()
  File "./accelerate/canny/canny", line 3997, in entry_main
    w_14971, low_14972, high_14973)
  File "./accelerate/canny/canny", line 3897, in futhark_main
    sync(self)
  File "./accelerate/canny/canny", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

Results for accelerate/crystal/crystal.fut:
dataset #0 ("200i32 30.0f32 5i32 1i32 1.0f32"):   accelerate/crystal/crystal.fut failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/crystal/crystal", line 3331, in <module>
    entry_point_fun()
  File "./accelerate/crystal/crystal", line 3248, in entry_main
    sync(self)
  File "./accelerate/crystal/crystal", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

dataset #4 ("2000i32 30.0f32 50i32 1i32 1.0f32"): accelerate/crystal/crystal.fut failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/crystal/crystal", line 3331, in <module>
    entry_point_fun()
  File "./accelerate/crystal/crystal", line 3248, in entry_main
    sync(self)
  File "./accelerate/crystal/crystal", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

dataset #5 ("4000i32 30.0f32 50i32 1i32 1.0f32"): accelerate/crystal/crystal.fut failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/crystal/crystal", line 3331, in <module>
    entry_point_fun()
  File "./accelerate/crystal/crystal", line 3248, in entry_main
    sync(self)
  File "./accelerate/crystal/crystal", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

Results for accelerate/fft/fft.fut:
dataset data/256x256.in:   accelerate/fft/fft failed with error code 1 and output:
Traceback (most recent call last):
  File "./accelerate/fft/fft", line 10524, in <module>
    entry_point_fun()
  File "./accelerate/fft/fft", line 10480, in entry_main
    sync(self)
  File "./accelerate/fft/fft", line 222, in sync
    raise Exception(self.failure_msgs[failure[0]].format(*failure_args))
IndexError: list index out of range

dataset data/128x512.in:   ^C
[vgh804@gpu02-diku-apl futhark-benchmarks]$
```
This was futhark version 0.15.0. I was doing this to test how pyopencl compares to the opencl backend. Is there any place where I can see the backends performance compared? Do they have similar performance or is OpenCL backend far better?

**Comment by athas** [comment]
I think this is fixed in the newest version of the compiler.  The PyOpenCL backend is often much slower, depending on the program.
